ffajobsdb/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
   url(r'^', include('jobsdb.urls', namespace="jobsdb")),
   url(r'^admin/', admin.site.urls),
]

jobsdb/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
     url(r'^$', views.IndexView.as_view(), name='index'),
     url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='connection_list'),
]

jobsdb/models.py
from __future__ import unicode_literals
import json
from django.db import models
from django.http import JsonResponse


class Location(models.Model):
    location_name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.location_name
   
class Connection(models.Model):
    base= models.CharField(max_length=200)	
    location = models.ForeignKey(Location)
    ip = models.CharField(max_length=200)
    port = models.IntegerField(default=0)
    mfdbname= models.CharField(max_length=200)
    bfdbname= models.CharField(max_length=200)

    def __str__(self):
        return self.ip

jobsdb/views.py
from django.shortcuts import render

from django.http import HttpResponse
import json
from django.http import JsonResponse
from django.views import generic

from .models import Location, Connection


class IndexView( generic.ListView):
    template_name = 'jobsdb/index.html'
    context_object_name = 'location_list'
    model= Location
    

    def get_queryset(self):
        """Return the  location by order alphabetic."""
        return Location.objects.order_by('id')
   


    def get(self, *args, **kwargs):
    
        asjson = self.request.GET.get('asjson', "false")
        asjson=asjson.lower()=="true"
          
        if not asjson:
            return super(IndexView, self).get(*args, **kwargs)
        #https://stackoverflow.com/questions/39768671/how-to-return-jsonresponse-in-django-generic-listview
        
       
        #Get a specific fileds from queryset
        #https://docs.djangoproject.com/en/1.7/topics/serialization/
        
        data = [{"location_id": location.id, "location_name": location.location_name} for location in Location.objects.all()]
        
        return JsonResponse(data,safe=False)



class DetailView(generic.DetailView):
      model = Location
      template_name = 'jobsdb/connection_list.html'



      def get(self, *args, **kwargs):

          
       
          #http://programtalk.com/vs2/python/2464/django-completion/completion/views.py/
          asjson = self.request.GET.get('asjson', "false")
          asjson=asjson.lower()=="true"
          
          if not asjson:
              return super(DetailView, self).get(*args, **kwargs)

          #https://stackoverflow.com/questions/34460708/checkoutview-object-has-no-attribute-object
          self.object = self.get_object()
          context = super(DetailView, self).get_context_data(**kwargs)
          location = context["location"]
          output = {
           
            "location_name": location.location_name,
            "connection_set": [[x.base,x.ip] for x in location.connection_set.all()]
          }
          return JsonResponse(output)

jobsdb/templates/jobsdb/connection_list.html
<HTML>
<HEAD>
<title>FFA Private Bank - Jobs Database</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

</HEAD>
<body style="MARGIN: 0px">


<table cellSpacing="0" cellPadding="0" width="779" align="center" border="0" >
	<TBODY>
		<tr>
	
			<td align="center">
				<table cellSpacing="0" cellPadding="0" width="779" border="0">
				<TBODY>
			
		<tr><td><br>
<a  href="{% url 'jobsdb:index' %}" style="text-decoration: none">Home</a>&nbsp; |&nbsp;<a  href="{% url 'admin:index' %}" style="text-decoration: none">Admin</a>&nbsp;|&nbsp;<a  href="https://github.com/minerva22/ffa-jobs-db/" style="text-decoration: none">GitHub Link</a></td>
</tr>
					
<tr>
						<td><br>
							<table cellSpacing="0" cellPadding="0" width="780" bgColor="#f1f1f1" border="0">
								<tr>
									<td align="left"><font size="5" color="#04366C"><b>FFA Private Bank sal</b></font>
									</td>

								</tr>
								<tr>
									<td align="right">&nbsp;</td>
								</tr>
							</table>
						</td>
					</tr>
				</TBODY>

				</table>
                        </td>
		</tr>
	<tr>
			<td>

				<table cellSpacing="0" cellPadding="0" border="0" align="center" width="779">
					<tr>
						<td align = "center" height="25" width ="200">
						<div align="center">
						<FONT color="#ffffff"><MARQUEE bgcolor="#04366C" direction="left" loop="50" width="780" scrolldelay="150">
						<STRONG>FFA Private Bank Jobs Database</STRONG></MARQUEE></FONT></DIV>
						</td>

				</table>
			</td>
		</tr>

		<tr>
			<td height="12">
			</td>
		</tr>
               <tr>
			<td >

				<table cellSpacing="0" cellPadding="0" width="779" align="center" border="0">
					
					<tr >
						<td align="left" ><font size="3.5" color="#04366C"><b>{{ location.location_name }} </li>
						</td> </b></font>
<!-- <a href=%}" <button>Continue</button></a> </td> -->
					</tr>
					
					<tr>
						<td>
							<table> 
									
								 <tr>
 																	
									<td height="12" >
											<ul>
											{% for connection in location.connection_set.all %}
											</ul>
									</td>
									
								</tr>

								 <tr>
								  <td height="30" >
								   Base:: {{ connection.base }}<br>
    								   Ip: {{ connection.ip }}<br>
							           Port: {{ connection.port }} <br>
								   Mfdbname: {{ connection.mfdbname }}<br>
							           Bfdbname: {{ connection.bfdbname }}<br><br>
									</td>
									
								 </tr>
								{% endfor %}
								

							</table>
						</td>
						
					</tr>

				</table>
			</td>
		</tr>
		<tr>
			<td>
				<table height="50" cellSpacing="0" cellPadding="0" width="100%" border="0">
					<tr>
						<td height="12"  style=" BORDER-top: #ffffff 1px solid; "></td>
					</tr>

					<tr>
						<td height="4"  style=" BORDER-top: #ffffff 1px solid; " bgColor="#04366C"></td>
					</tr>
					<tr>
						<td bgColor="#f1f1f1" align ="right"><FONT color="#04366C" size="2">&nbsp;Developed by: Minerva Moawad - 2017&nbsp;</FONT></td>
					</tr>

				</table>
			</td>
		</tr>
		
	</TBODY>
</table>

</body>

</html>

jobsdb/templates/jobsdb/index.html
<HTML>
<HEAD>
<title>FFA Private Bank - Jobs Database</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

</HEAD>
<body style="MARGIN: 0px">


<table cellSpacing="0" cellPadding="0" width="779" align="center" border="0" >
	<TBODY>
		<tr>
	
			<td align="center">
				<table cellSpacing="0" cellPadding="0" width="779" border="0">
				<TBODY><br>
			
	<tr><td>
<a  href="{% url 'jobsdb:index' %}" style="text-decoration: none">Home</a>&nbsp; |&nbsp;<a  href="{% url 'admin:index' %}" style="text-decoration: none">Admin</a>&nbsp;|&nbsp;<a  href="https://github.com/minerva22/ffa-jobs-db/" style="text-decoration: none">GitHub Link</a></td>
</tr>
					
<tr>
						<td><br>
							<table cellSpacing="0" cellPadding="0" width="780" bgColor="#f1f1f1" border="0">
								<tr>
									<td align="left"><font size="5" color="#04366C"><b>FFA Private Bank sal</b></font>
									</td>

								</tr>
								<tr>
									<td align="right">&nbsp;</td>
								</tr>
							</table>
						</td>
					</tr>
				</TBODY>

				</table>
                        </td>
		</tr>
	<tr>
			<td>

				<table cellSpacing="0" cellPadding="0" border="0" align="center" width="779">
					<tr>
						<td align = "center" height="25" width ="200">
						<div align="center">
						<FONT color="#ffffff"><MARQUEE bgcolor="#04366C" direction="left" loop="50" width="780" scrolldelay="150">
						<STRONG>FFA Private Bank Jobs Database</STRONG></MARQUEE></FONT></DIV>
						</td>

				</table>
			</td>
		</tr>

		<tr>
			<td height="12">
			</td>
		</tr>
                <tr><td><h4>Locations</h4>
					{% if location_list %}
    						<ul>
   					 {% for location in location_list %}
					
    					 <tr> 
						<td>  <li> <a href="{% url 'jobsdb:connection_list' location.id %}">{{ location.location_name }}</a>  
</td>
     					{% endfor %}
  						 </ul>
					{% else %}
    					<p>No locations are available.</p>
					{% endif %}

					
		<tr>
			<td>
				<table height="50" cellSpacing="0" cellPadding="0" width="100%" border="0">
					<tr>
						<td height="12"  style=" BORDER-top: #ffffff 1px solid; "></td>
					</tr>

					<tr>
						<td height="4"  style=" BORDER-top: #ffffff 1px solid; " bgColor="#04366C"></td>
					</tr>
					<tr>
						<td bgColor="#f1f1f1" align ="right"><FONT color="#04366C" size="2">&nbsp;Developed by: Minerva Moawad - 2017&nbsp;</FONT></td>
					</tr>

				</table>
			</td>
		</tr>
		
	</TBODY>
</table>

</body>

</html>